name: Deploy GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies(Vite项目)
        working-directory: ./Download
        run: npm install

      - name: Build vite
        working-directory: ./Download
        run: npm run build

      - name: Copy static assets into dist
        run: |
          mkdir -p ./dist
          cp -v ../*.html ../*.data ../CNAME ../README.md ./dist/
        working-directory: ./Download

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Download/dist
